apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kdb-wac-fe-content
spec:
  microFrontend: kdb-wac-fe
  element: app-component
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?kdb-app(/.*)?$"