apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kdb-wac-fe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Sledovanie výkonov v rámci jednotlivých ambulancií a ich ekonomické náklady
    - name: short-headline
      value: Sledovanie výkonov v rámci jednotlivých ambulancií a ich ekonomické náklady
    - name: supporting-text
      value: |
        Sledovanie výkonov v rámci jednotlivých ambulancií a ich ekonomické náklady
    - name: material-icon
      value: home_health
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./kdb-app
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
        - context-name: applications
        - context-name: rail-content
        - context-name: drawer-content