apiVersion: v1
kind: Secret
metadata:
  name: repository-pat
  namespace: wac-hospital

type: Opaque
stringData:
  username: 'xdudakm' # zvyčajne môže byť akékoľvek meno
  password: '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'  # vygenerovaný PAT