apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdb-wac-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /kdb-openapi
            - name: BASE_URL
              value: /kdb-openapi-ui